### ISSUE TITLE
Bump scio to 0.9.0

### ISSUE THREAD

**Issue by dilyand** [snowplow-incubator/snowplow-bigquery-loader#86]

**Comment by dilyand** [comment]
Causes:

```
Exception in thread "main" java.lang.RuntimeException: Failed to construct instance from factory method DataflowRunner#fromOptions(interface org.apache.beam.sdk.options.PipelineOptions)
	at org.apache.beam.sdk.util.InstanceBuilder.buildFromMethod(InstanceBuilder.java:224)
	at org.apache.beam.sdk.util.InstanceBuilder.build(InstanceBuilder.java:155)
	at org.apache.beam.sdk.PipelineRunner.fromOptions(PipelineRunner.java:55)
	at org.apache.beam.sdk.Pipeline.create(Pipeline.java:149)
	at com.spotify.scio.ScioContext.pipeline(ScioContext.scala:498)
	at com.spotify.scio.ScioContext.applyInternal(ScioContext.scala:675)
	at com.spotify.scio.ScioContext.applyInternal(ScioContext.scala:680)
	at com.spotify.scio.io.StringPubsubIOWithoutAttributes.read(PubsubIO.scala:206)
	at com.spotify.scio.io.StringPubsubIOWithoutAttributes.read(PubsubIO.scala:199)
	at com.spotify.scio.io.ScioIO$$anonfun$readWithContext$1.apply(ScioIO.scala:77)
	at com.spotify.scio.io.ScioIO$$anonfun$readWithContext$1.apply(ScioIO.scala:74)
	at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:657)
	at com.spotify.scio.io.ScioIO.readWithContext(ScioIO.scala:74)
	at com.spotify.scio.io.ScioIO.readWithContext$(ScioIO.scala:70)
	at com.spotify.scio.io.StringPubsubIOWithoutAttributes.readWithContext(PubsubIO.scala:199)
	at com.spotify.scio.ScioContext.read(ScioContext.scala:794)
	at com.spotify.scio.ScioContext.pubsubIn(ScioContext.scala:702)
	at com.spotify.scio.ScioContext.pubsubSubscription(ScioContext.scala:714)
	at com.snowplowanalytics.snowplow.storage.bigquery.loader.Loader$.getData(Loader.scala:137)
	at com.snowplowanalytics.snowplow.storage.bigquery.loader.Loader$.run(Loader.scala:61)
	at com.snowplowanalytics.snowplow.storage.bigquery.loader.Main$.main(Main.scala:24)
	at com.snowplowanalytics.snowplow.storage.bigquery.loader.Main.main(Main.scala)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.beam.sdk.util.InstanceBuilder.buildFromMethod(InstanceBuilder.java:214)
	... 21 more
Caused by: java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.expireAfterWrite(Ljava/time/Duration;)Lcom/google/common/cache/CacheBuilder;
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.<init>(GoogleCloudStorageImpl.java:149)
	at org.apache.beam.sdk.extensions.gcp.util.GcsUtil.<init>(GcsUtil.java:243)
	at org.apache.beam.sdk.extensions.gcp.util.GcsUtil.<init>(GcsUtil.java:82)
	at org.apache.beam.sdk.extensions.gcp.util.GcsUtil$GcsUtilFactory.create(GcsUtil.java:104)
	at org.apache.beam.sdk.extensions.gcp.util.GcsUtil$GcsUtilFactory.create(GcsUtil.java:87)
	at org.apache.beam.sdk.options.ProxyInvocationHandler.returnDefaultHelper(ProxyInvocationHandler.java:592)
	at org.apache.beam.sdk.options.ProxyInvocationHandler.getDefault(ProxyInvocationHandler.java:533)
	at org.apache.beam.sdk.options.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:158)
	at com.sun.proxy.$Proxy24.getGcsUtil(Unknown Source)
	at org.apache.beam.sdk.extensions.gcp.options.GcpOptions$GcpTempLocationFactory.tryCreateDefaultBucket(GcpOptions.java:354)
	at org.apache.beam.sdk.extensions.gcp.options.GcpOptions$GcpTempLocationFactory.create(GcpOptions.java:300)
	at org.apache.beam.sdk.extensions.gcp.options.GcpOptions$GcpTempLocationFactory.create(GcpOptions.java:288)
	at org.apache.beam.sdk.options.ProxyInvocationHandler.returnDefaultHelper(ProxyInvocationHandler.java:592)
	at org.apache.beam.sdk.options.ProxyInvocationHandler.getDefault(ProxyInvocationHandler.java:533)
	at org.apache.beam.sdk.options.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:158)
	at com.sun.proxy.$Proxy16.getGcpTempLocation(Unknown Source)
	at org.apache.beam.runners.dataflow.DataflowRunner.fromOptions(DataflowRunner.java:249)
	... 26 more
```

**Comment by dilyand** [comment]
Superseded by https://github.com/snowplow-incubator/snowplow-bigquery-loader/issues/114
